import { PersonalityConfig } from '../types';

export const DEFAULT_PERSONALITIES: PersonalityConfig[] = [
  {
    id: 'conservative',
    name: 'Conservative',
    description: 'High probability trades only, profit-gated, limited frequency',
    isActive: true,
    minProbability: 0.55,
    maxDailyTrades: 3,
    entryDelaySeconds: 300,
    allowedStrategies: ['NON_DIRECTIONAL'],
    allowedUnderlyings: ['NIFTY', 'BANKNIFTY'],
    maxLossPerTrade: 2500,
    maxDailyLoss: 4000,
    positionSizeMultiplier: 1.0,
    requireProfitGate: true,
    profitGateThreshold: 0,
    profitGateLookbackDays: 5,
    allowedTradingWindows: [
      { startTime: '09:20', endTime: '11:30' },
      { startTime: '14:00', endTime: '15:00' },
    ],
    blockedDates: [],
    allowedRegimes: ['LOW_VOL', 'HIGH_VOL', 'RANGEBOUND'],
    maxVix: 25,
    minVix: 8,
    allowReentry: false,
    reentryDelayMinutes: 0,
    maxReentriesPerSignal: 0,
    version: 1,
    parentVersion: null,
    evolutionReason: null,
    performanceMetrics: {
      winRate30d: 0,
      totalPnL30d: 0,
      sharpe30d: 0,
      maxDrawdown30d: 0,
      tradesCount30d: 0,
      lastUpdated: new Date(),
    },
  },
  {
    id: 'balanced',
    name: 'Balanced',
    description: 'Moderate probability threshold, reasonable frequency',
    isActive: true,
    minProbability: 0.60,
    maxDailyTrades: 4,
    entryDelaySeconds: 120,
    allowedStrategies: ['NON_DIRECTIONAL', 'DIRECTIONAL'],
    allowedUnderlyings: ['NIFTY', 'BANKNIFTY'],
    maxLossPerTrade: 3500,
    maxDailyLoss: 8000,
    positionSizeMultiplier: 1.0,
    requireProfitGate: false,
    profitGateThreshold: 0,
    profitGateLookbackDays: 0,
    allowedTradingWindows: [{ startTime: '09:17', endTime: '15:15' }],
    blockedDates: [],
    allowedRegimes: ['LOW_VOL', 'HIGH_VOL', 'RANGEBOUND'],
    maxVix: 25,
    minVix: 8,
    allowReentry: true,
    reentryDelayMinutes: 15,
    maxReentriesPerSignal: 1,
    version: 1,
    parentVersion: null,
    evolutionReason: null,
    performanceMetrics: {
      winRate30d: 0,
      totalPnL30d: 0,
      sharpe30d: 0,
      maxDrawdown30d: 0,
      tradesCount30d: 0,
      lastUpdated: new Date(),
    },
  },
  {
    id: 'aggressive',
    name: 'Aggressive',
    description: 'Low probability threshold, high frequency, all regimes',
    isActive: true,
    minProbability: 0.45,
    maxDailyTrades: 8,
    entryDelaySeconds: 30,
    allowedStrategies: ['NON_DIRECTIONAL', 'DIRECTIONAL'],
    allowedUnderlyings: ['NIFTY', 'BANKNIFTY', 'SENSEX'],
    maxLossPerTrade: 5000,
    maxDailyLoss: 15000,
    positionSizeMultiplier: 1.5,
    requireProfitGate: false,
    profitGateThreshold: 0,
    profitGateLookbackDays: 0,
    allowedTradingWindows: [{ startTime: '09:15', endTime: '15:25' }],
    blockedDates: [],
    allowedRegimes: ['LOW_VOL', 'HIGH_VOL', 'TRENDING', 'RANGEBOUND'],
    maxVix: 40,
    minVix: 0,
    allowReentry: true,
    reentryDelayMinutes: 5,
    maxReentriesPerSignal: 3,
    version: 1,
    parentVersion: null,
    evolutionReason: null,
    performanceMetrics: {
      winRate30d: 0,
      totalPnL30d: 0,
      sharpe30d: 0,
      maxDrawdown30d: 0,
      tradesCount30d: 0,
      lastUpdated: new Date(),
    },
  },
];

export const DEFAULT_CHARGE_STRUCTURE = {
  brokeragePer100k: 0.0003,   // 0.03% per side (Zerodha-like flat fee model)
  stt: 0.0001,                // 0.01% on sell turnover
  exchangeFee: 0.0000053,     // NSE transaction charge
  gst: 0.18,                  // 18% on brokerage + exchange fee
  sebiTurnover: 10,           // ₹10 per crore
  stampDuty: 0.00003,         // 0.003% on buy
};
